In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\Movies-PD-Projects\data\movies_metadata_cleaned.csv")

In [3]:
df.head()

,id,title,tagline,overview,release_date,runtime,genres,original_language,spoken_languages,cast,director,production_companies,production_countries,belongs_to_collection,revenue,budget,vote_count,vote_average,popularity,status
0,862,Toy Story,No Tagline,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,Animation|Comedy|Family,en,English,Woody (voice) as Tom Hanks|Buzz Lightyear (voi...,John Lasseter,Pixar Animation Studios,United States of America,Toy Story Collection,373554033.0,30000000.0,5415.0,7.7,21.946943,Released
1,8844,Jumanji,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,Adventure|Fantasy|Family,en,English|Français,Alan Parrish as Robin Williams|Samuel Alan Par...,Joe Johnston,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,No Collection,262797249.0,65000000.0,2413.0,6.9,17.015539,Released
2,15602,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,1995-12-22,101.0,Romance|Comedy,en,English,Max Goldman as Walter Matthau|John Gustafson a...,Howard Deutch,Warner Bros.|Lancaster Gate,United States of America,Grumpy Old Men Collection,0.0,0.0,92.0,6.5,11.712900,Released
3,31357,Waiting to Exhale,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,Comedy|Drama|Romance,en,English,Savannah 'Vannah' Jackson as Whitney Houston|B...,Forest Whitaker,Twentieth Century Fox Film Corporation,United States of America,No Collection,81452156.0,16000000.0,34.0,6.1,3.859495,Released
4,11862,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,1995-02-10,106.0,Comedy,en,English,George Banks as Steve Martin|Nina Banks as Dia...,Charles Shyer,Sandollar Productions|Touchstone Pictures,United States of America,Father of the Bride Collection,76578911.0,0.0,173.0,5.7,8.387519,Released

In [4]:
min_value = 5 

df
df = df.fillna('').replace({'Unknown': '', 'No Overview': '', 'No Tagline': '', 'No Collection': ''})
df['release_date'] = pd.to_datetime(df['release_date'], format='%Y-%m-%d', errors='coerce')
df['year'] = df['release_date'].dt.year
df.loc[df['year'] < 1854, 'year'] = np.nan
df= df[df['vote_count']>=min_value].reset_index(drop=True)
df.head()

,id,title,tagline,overview,release_date,runtime,genres,original_language,spoken_languages,cast,...,production_companies,production_countries,belongs_to_collection,revenue,budget,vote_count,vote_average,popularity,status,year
0,862,Toy Story,,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,Animation|Comedy|Family,en,English,Woody (voice) as Tom Hanks|Buzz Lightyear (voi...,...,Pixar Animation Studios,United States of America,Toy Story Collection,373554033.0,30000000.0,5415.0,7.7,21.946943,Released,1995.0
1,8844,Jumanji,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,Adventure|Fantasy|Family,en,English|Français,Alan Parrish as Robin Williams|Samuel Alan Par...,...,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,,262797249.0,65000000.0,2413.0,6.9,17.015539,Released,1995.0
2,15602,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,1995-12-22,101.0,Romance|Comedy,en,English,Max Goldman as Walter Matthau|John Gustafson a...,...,Warner Bros.|Lancaster Gate,United States of America,Grumpy Old Men Collection,0.0,0.0,92.0,6.5,11.712900,Released,1995.0
3,31357,Waiting to Exhale,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,Comedy|Drama|Romance,en,English,Savannah 'Vannah' Jackson as Whitney Houston|B...,...,Twentieth Century Fox Film Corporation,United States of America,,81452156.0,16000000.0,34.0,6.1,3.859495,Released,1995.0
4,11862,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,1995-02-10,106.0,Comedy,en,English,George Banks as Steve Martin|Nina Banks as Dia...,...,Sandollar Productions|Touchstone Pictures,United States of America,Father of the Bride Collection,76578911.0,0.0,173.0,5.7,8.387519,Released,1995.0

In [5]:
df.info

<bound method DataFrame.info of            id                             title  \
0         862                         Toy Story
1        8844                           Jumanji
2       15602                  Grumpier Old Men
3       31357                 Waiting to Exhale
4       11862       Father of the Bride Part II
...       ...                               ...
30874  106807  The Fat and Lean Wrestling Match
30875  404604                               Mom
30876   84419                  House of Horrors
30877   30840                        Robin Hood
30878   67758                          Betrayal

                                                 tagline  \
0
1              Roll the dice and unleash the excitement!
2      Still Yelling. Still Fighting. Still Ready for...
3      Friends are the people who let you be yourself...
4      Just When His World Is Back To Normal... He's ...
...                                                  ...
30874
30875
30876                                Meet...The CREEPER!
30877
30878                             A deadly game of wits.

                                                overview release_date  \
0      Led by Woody, Andy's toys live happily in his ...   1995-10-30
1      When siblings Judy and Peter discover an encha...   1995-12-15
2      A family wedding reignites the ancient feud be...   1995-12-22
3      Cheated on, mistreated and stepped on, the wom...   1995-12-22
4      Just when George Banks has recovered from his ...   1995-02-10
...                                                  ...          ...
30874         A series of fantastical wrestling matches.   1900-01-01
30875  The bliss of a biology teacher’s family life i...   2017-07-07
30876  An unsuccessful sculptor saves a madman named ...   1946-03-29
30877  Yet another version of the classic epic, with ...   1991-05-13
30878  When one of her hits goes wrong, a professiona...   2003-08-01

       runtime                    genres original_language  spoken_languages  \
0         81.0   Animation|Comedy|Family                en           English
1        104.0  Adventure|Fantasy|Family                en  English|Français
2        101.0            Romance|Comedy                en           English
3        127.0      Comedy|Drama|Romance                en           English
4        106.0                    Comedy                en           English
...        ...                       ...               ...               ...
30874      2.0            Comedy|Fantasy                fr       No Language
30875    146.0      Crime|Drama|Thriller                hi            हिन्दी
30876     65.0   Horror|Mystery|Thriller                en           English
30877    104.0      Drama|Action|Romance                en           English
30878     90.0     Action|Drama|Thriller                en           English

                                                    cast  ...  \
0      Woody (voice) as Tom Hanks|Buzz Lightyear (voi...  ...
1      Alan Parrish as Robin Williams|Samuel Alan Par...  ...
2      Max Goldman as Walter Matthau|John Gustafson a...  ...
3      Savannah 'Vannah' Jackson as Whitney Houston|B...  ...
4      George Banks as Steve Martin|Nina Banks as Dia...  ...
...                                                  ...  ...
30874        as Jeanne d'Alcy|Wrestler as Georges Méliès  ...
30875  Devki Sabarwal as Sridevi Kapoor|Arya as Sajal...  ...
30876  The Creeper as Rondo Hatton|Steven Morrow as R...  ...
30877  Sir Robert Hode as Patrick Bergin|Maid Marian ...  ...
30878  Emily Shaw as Erika Eleniak|Det. Mark Winston ...  ...

                                    production_companies  \
0                                Pixar Animation Studios
1      TriStar Pictures|Teitler Film|Interscope Commu...
2                            Warner Bros.|Lancaster Gate
3                 Twentieth Century Fox Film Corporation
4              Sandollar Productions|Touchstone Pictures
...                                                  ...
30874                                          Star-Film
30875                       Mad Films|Third Eye Pictures
30876                                 Universal Pictures
30877  Westdeutscher Rundfunk (WDR)|Working Title Fil...
30878                            American World Pictures

                                    production_countries  \
0                               United States of America
1                               United States of America
2                               United States of America
3                               United States of America
4                               United States of America
...                                                  ...
30874                                             France
30875                                              India
30876                           United States of America
30877  Canada|Germany|United Kingdom|United States of...
30878                           United States of America

                belongs_to_collection      revenue      budget  vote_count  \
0                Toy Story Collection  373554033.0  30000000.0      5415.0
1                                      262797249.0  65000000.0      2413.0
2           Grumpy Old Men Collection          0.0         0.0        92.0
3                                       81452156.0  16000000.0        34.0
4      Father of the Bride Collection   76578911.0         0.0       173.0
...                               ...          ...         ...         ...
30874                                          0.0         0.0         6.0
30875                                          0.0         0.0        14.0
30876                                          0.0         0.0         8.0
30877                                          0.0         0.0        26.0
30878                                          0.0         0.0         6.0

       vote_average  popularity    status    year
0               7.7   21.946943  Released  1995.0
1               6.9   17.015539  Released  1995.0
2               6.5   11.712900  Released  1995.0
3               6.1    3.859495  Released  1995.0
4               5.7    8.387519  Released  1995.0
...             ...         ...       ...     ...
30874           6.5    0.225432  Released  1900.0
30875           6.6    1.559596  Released  2017.0
30876           6.3    0.222814  Released  1946.0
30877           5.7    5.683753  Released  1991.0
30878           3.8    0.903007  Released  2003.0

[30879 rows x 21 columns]>

In [6]:
crj = lambda x: ''.join(ch for ch in x.lower() if ch.isalnum())



df['genre_tokens'] = df['genres'].apply(lambda x:' '.join([crj(g) for g in x.split('|') ]))
df['cast_tokens'] = df['cast'].apply(lambda x:' '.join([crj(c.rsplit(' as ', 1)[-1]) for c in x.split('|') if c][:3]))
df['director_tokens'] = df['director'].apply(lambda x:' '.join([crj(d) for d in x.split(',') if d]))
df['collection_tokens'] = df['belongs_to_collection'].apply(crj)

df['meta_soup'] = df['genre_tokens'] + ' ' + df['cast_tokens'] + ' ' + df['director_tokens'] + ' ' + df['collection_tokens']

df['plot_soup'] = df['overview'] + ' ' + df['tagline']

In [7]:
df.head()

,id,title,tagline,overview,release_date,runtime,genres,original_language,spoken_languages,cast,...,vote_average,popularity,status,year,genre_tokens,cast_tokens,director_tokens,collection_tokens,meta_soup,plot_soup
0,862,Toy Story,,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,Animation|Comedy|Family,en,English,Woody (voice) as Tom Hanks|Buzz Lightyear (voi...,...,7.7,21.946943,Released,1995.0,animation comedy family,tomhanks timallen donrickles,johnlasseter,toystorycollection,animation comedy family tomhanks timallen donr...,"Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,Adventure|Fantasy|Family,en,English|Français,Alan Parrish as Robin Williams|Samuel Alan Par...,...,6.9,17.015539,Released,1995.0,adventure fantasy family,robinwilliams jonathanhyde kirstendunst,joejohnston,,adventure fantasy family robinwilliams jonatha...,When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,1995-12-22,101.0,Romance|Comedy,en,English,Max Goldman as Walter Matthau|John Gustafson a...,...,6.5,11.712900,Released,1995.0,romance comedy,waltermatthau jacklemmon annmargret,howarddeutch,grumpyoldmencollection,romance comedy waltermatthau jacklemmon annmar...,A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,Comedy|Drama|Romance,en,English,Savannah 'Vannah' Jackson as Whitney Houston|B...,...,6.1,3.859495,Released,1995.0,comedy drama romance,whitneyhouston angelabassett lorettadevine,forestwhitaker,,comedy drama romance whitneyhouston angelabass...,"Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,1995-02-10,106.0,Comedy,en,English,George Banks as Steve Martin|Nina Banks as Dia...,...,5.7,8.387519,Released,1995.0,comedy,stevemartin dianekeaton martinshort,charlesshyer,fatherofthebridecollection,comedy stevemartin dianekeaton martinshort cha...,Just when George Banks has recovered from his ...

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import normalize
from scipy.sparse import hstack

In [ ]:
meta_value , plot_value = 0.6, 0.4

meta_matrix = normalize(CountVectorizer(token_pattern=r'\S+').fit_transform(df['meta_soup'])) 

plot_matrix = TfidfVectorizer( min_df=2,stop_words='english',max_features=30000,sublinear_tf=True).fit_transform(df['plot_soup']) 

matrix = normalize(hstack([meta_value * meta_matrix, plot_value * plot_matrix]).tocsr())

print('Matrix shape:', matrix.shape)

Matrix shape: (30879, 77822)